language: csharp
solution: NG_GameSim.sln
before_install:
  - wget https://github.com/cra0zy/monodevelop-run-installer/releases/download/6.2.0.1778-1/monodevelop-6.2.0.1778-1.run
  - chmod +x monodevelop-6.2.0.1778-1.run
  - wget http://www.monogame.net/releases/v3.6/monogame-sdk.run
  - chmod +x monogame-sdk.run
  - mono Protobuild.exe --generate
install:
  - sudo ./monodevelop-6.2.0.1778-1.run
  - yes Y|sudo ./monogame-sdk.run 
  # - sudo apt-get install -qq monodevelop libopenal-dev referenceassemblies-pcl ttf-mscorefonts-installer gtk-sharp2; # install needed packages for the monogame sdk
  # - sudo ./generate.sh && yes Y|sudo ./monogame-linux.run; # install monogame sdk
script:
  - mono Protobuild.exe --build
  # - (cd Project/Content && mono /opt/monogame-pipeline/MGCB.exe /rebuild /@:"Content.mgcb" /outputDir:"../bin/Release/Content") 